#!/bin/sh

#
# Init script to start and stop the aesdsocket
#

start() {
    echo "Starting aesdsocket..."
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    echo "OK"
}

stop() {
    echo "Stopping aesdsocket..."
    start-stop-daemon -K -n aesdsocket
    echo "OK"
}

restart() {
    echo "Restarting aesdsocket"
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart | reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
