#!/bin/sh

start() {
	echo "START program with daemon mode.."
	start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
}

stop() {
	echo "STOP daemon program.."
	start-stop-daemon -K -n aesdsocket
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
